[package]
name = "hahaha"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
kube = { version = "0.68", features = ["runtime","derive","ws"] }
hyper = "0.14"
k8s-openapi = { version = "0.14.0", default-features = false, features = ["v1_19"] }
anyhow = "1.0.44"
futures = "0.3.17"
tracing = "0.1"
tracing-subscriber = "0.2"
async-trait = "0.1.51"