[package]
name = "hahaha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
kube = { version = "0.63.2", features = ["runtime","derive","ws"] }
k8s-openapi = { version = "0.13.0", default-features = false, features = ["v1_19"] }
anyhow = "1.0.44"
futures = "0.3.17"
tracing = "0.1"
tracing-subscriber = "0.2"
tokio-util = "0.6.8"