---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hahaha
  labels:
    app: hahaha
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/portforward
    verbs:
      - create
      - get
      - list
  
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
