apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{.Release.Name}}
  labels:
    team: {{ .Release.Namespace }}
    {{- include "hahaha.labels" . | nindent 4 }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  port: 8999
  prometheus:
    enabled: true
    path: /
