{{ if .Values.alert.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{.Release.Name}}
  labels:
    {{- include "hahaha.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{.Release.Name }}
      rules:
        - alert: HAHAHA hasn't turned off any sidecars the past 15 minutes
          expr: sum(increase(hahaha_sidecar_shutdowns[15m])) < 0.5
          for: 5m
          annotations:
            action: "Check logs:\n- `kubectl logs -n aura $(kubectl get pod -n aura -l app=hahaha --no-headers -o custom-columns=\":metadata.name\") hahaha`\n\nA restart of HAHAHA will likely solve the issue."
            summary: "HAHAHA hasn't turned off any sidecars recently, which means that Pods created by Naisjobs won't be cleaned up."
          labels:
            namespace: {{  .Release.Namespace }}
            severity: critical
{{ end }}
