---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Release.Name}}-apiserver
  labels:
    {{- include "hahaha.labels" . | nindent 4 }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.apiServerCIDR }}
  podSelector:
    matchLabels:
      {{- include "hahaha.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
