apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: aura
  annotations:
    nais.io/naisjob: "true"
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
  name: oh-no
  namespace: aura
spec:
  image: navikt/perl
  schedule: "0/5 * * * *"
  command: ["perl", "-le", "sleep(40);print 'job complete'"]
  secureLogs:
    enabled: true
