name: Build and deploy test job
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
         - dev-gcp
    steps:
    - uses: actions/checkout@v1
    - name: deploy to ${{ matrix.cluster }}
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: ${{ matrix.cluster }}
        RESOURCE: test-specs/job.yaml
