name: Deploy Naisjob /w schedule
on:
  push:
    branches:
      - 'main'
    paths:
      - 'test-specs/naisjob.yaml'
      - '.github/workflows/naisjob.yaml'

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
         - dev-gcp
         - prod-gcp
         - dev-fss
         - prod-fss
    steps:
    - uses: actions/checkout@v1
    - name: deploy to ${{ matrix.cluster }}
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: ${{ matrix.cluster }}
        RESOURCE: test-specs/naisjob.yaml
